backend:
  name: github
  repo: Jocsan091/PAGUINA-ESCUELA-ESPERANZA
  branch: main

local_backend: true

media_folder: "public/images/noticias"
public_folder: "/images/noticias"

collections:
  - name: "noticias"
    label: "Noticias"
    folder: "src/content/noticias"
    create: true
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}"
    extension: "md"
    format: "frontmatter"
    fields:
      - label: "Titulo"
        name: "title"
        widget: "string"
        required: true

      - label: "Imagen"
        name: "image"
        widget: "image"
        required: true

      - label: "Texto"
        name: "body"
        widget: "markdown"
        required: true
